all: /bin/vsockcom /bin/klog /bin/vsocktap

/bin/vsockcom: vsockcom.c
	gcc vsockcom.c -o /bin/vsockcom

/bin/vsocktap: vsocktap.c
	gcc vsocktap.c -o /bin/vsocktap

/bin/klog: klog.c
	gcc klog.c -o /bin/klog
	